### ISSUE TITLE
Rehosted images not added to user's account.

### ISSUE THREAD

**Issue by MrEnigmamgine** [graemephi/imgur-uploader#8] opened 2022-06-14 04:39 UTC
When using the context menu to rehost an image the image is successfully rehosted to imgur, however it is not added to the user's posts despite the extension being authorized in the user's account.

**Comment by MrEnigmamgine** [comment] 2022-06-14 05:07
Sorry for the double tap.

I did a bit of quick research on the project's code and I noticed in `options.js` there is a function called `checkAndDisplayAuthorization()` that is supposed to display the authenticated account if there is one.  However, for me the options applet always displays the *authenticate* button.

![example](https://i.imgur.com/25scium.png)

I believe what's happening here is that when the user authenticates to imgur, the access token is not being properly saved in the extension's settings.  Leading users to believe they are using the extension while authenticated even though they are not.

**Comment by graemephi** [comment] 2022-06-14 17:25
The authentication flow is still working on my end

Two questions: after authenticating with imgur, are you redirected back to the embedded options page with your username displayed, and does the extension appear in [your list of authenticated apps on imgur](https://imgur.com/account/settings/apps)?

If yes to both of those, then you're correct that your access token is not being saved somehow. But I have no idea how that could happen. Otherwise, probably the extension isn't receiving the access token at all or you are not actually authed with imgur. If you open the developer tools for the service worker and options.html (you need to open the chrome extensions page twice to see that one), there may be messages in the console there that can explain what is going on.

**Comment by MrEnigmamgine** [comment] 2022-06-15 03:43
The authentication flow does result in the app being listed in my list of authenticated apps on imgur and the redirect does send me back to the extensions tab. However, the embedded options page does not update to show my username.  Also.. the console is dead silent even when I enable the option to collect errors.

On the chrome web store there are a couple of people reporting similar issues so I'm surprised you aren't able to recreate the issue.  I'm using Chrome Version 102.0.5005.115. (latest afaik).

-------------
Below is additional information that may or may not be helpful.
-------------
Also, to add another wrinkle to the whole thing:  I forked the repository and loaded the extension unpacked to my own chrome, and after registering my client-id and secret with imgur I tried authenticating. I messed something up on the redirect url because I get a dns error 

This might be helpful.  I'm not sure what you have the app's redirect url set to in imgur, but mine is `https://www.getpostman.com/oauth2/callback` and when I try authenticating I get this as part of the redirect url  
` https://fhbjgbiflinjbdggehcddcbncdddomop.chromiumapp.org/oauth2-request?result=failure&message=Could+not+make+access+token+requests.The+feature+has+been+deprecated,please+download+the+latest+Postman+app#access_token=<my access token> `

I should point out that I'm an absolute noob to js, api, oath, and extension development so I'm sure that I'm not doing something right.. I mean I probably have no right to be even poking around.. but so far my money is on the idea that chrome's extension api might have changed.. or imgur's authorization might have changed.

I found this, but I haven't been able to make sense of it so far. https://stackoverflow.com/questions/34420459/what-redirect-url-can-i-set-for-oauth2-callback-in-a-chrome-extension

**Comment by graemephi** [comment] 2022-06-15 19:34
Yeah I'm on 102.0.5005.115 and can't trigger this issue at all, so I'm in the dark here. I appreciate you poking about

The redirect is set to the URL of the options page (`chrome-extension://lcpkicdemehhmkjolekhlglljnkggfcf/options.html`, where lcpki... is the extension ID). I set it up that way back in 2014--it doesn't use any of Chrome's OAuth APIs at all.

If you got as far as registering your own client id you know everything you need for this extension, its very simple

One thing it might be is [this message](https://github.com/graemephi/imgur-uploader/blob/8ca713ea119fe8c5f2eaec3a470056b9580b43eb/src/js/options.js#L37) isn't being received [here](https://github.com/graemephi/imgur-uploader/blob/8ca713ea119fe8c5f2eaec3a470056b9580b43eb/src/js/options.js#L53) for some reason, maybe due to closing the tab too soon after sending the message. That sounds racy and bugs that only repro on certain machines tend to be racy, so just commenting out line 38 and seeing what happens is the first thing I would do if I could reproduce this

**Comment by MrEnigmamgine** [comment] 2022-06-16 00:42
Yep. Setting up my redirect url properly and commenting out line 38 allowed me to authenticate like a charm on my testing fork.

I'm guessing that the  `chrome.runtime.sendMessage()` function is asynchronous and losing access to the tab before the promise is returned.    

I tested it and it definitely returns a promise (which I understand to mean it's an async function).  Unfortunately chrome just throws an expected keyword 'await' error if you try to say `await chrome.runtime.sendMessage()`

**Comment by graemephi** [comment] 2022-06-19 22:28
I've updated the version on the webstore with this fix so you should get the update in a few days after it passes review. Thanks for the help

**Closed as completed by graemephi** 2022-06-19 22:28 UTC
